workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Setup project
        script: |
          cp pubspec.yaml pubspec.yaml.bak
          cp -r lib lib.bak
          rm -rf android ios linux macos windows web
          flutter create --platforms android --project-name zakat_calculator --org com.mizanzakat .
          cp pubspec.yaml.bak pubspec.yaml
          rm -rf lib
          cp -r lib.bak lib
      - name: Get dependencies
        script: flutter pub get
              - flutter pub run flutter_launcher_icons
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - arshadfaisal786@gmail.com
